'''
Coding Just for Fun
Created by burness on 16/4/16.
'''

origin_data_path = "../data/"
song_file = origin_data_path+"mars_tianchi_songs.csv"
action_file = origin_data_path+'mars_tianchi_user_actions.csv'
train_data_file = origin_data_path+'train_data.csv'
is_holiday_file = origin_data_path+'is_holiday.csv'
test_result_file = origin_data_path+'test_result.csv'
temp_pivot_file = origin_data_path+'temp_pivot.csv'
temp_user_hour_pivot_file = origin_data_path+'temp_user_hour_pivot.csv'
singer_user_song_final_file = origin_data_path+'singer_user_song_final.csv'
temp_file = origin_data_path+'temp.csv'
artist_language_file = origin_data_path+'artist_language.csv'
artist_holiday_file = origin_data_path+'artist_holiday.csv'
date_holiday_file = origin_data_path + 'date_feature.csv'
all_data_file = origin_data_path + 'all_data.csv'
all_data_fileV2 = origin_data_path + 'all_dataV2.csv'
all_data_fileV3 = origin_data_path + 'all_dataV3.csv'
all_data_fileV4 = origin_data_path + 'all_dataV4.csv'
all_data_fileV5 = origin_data_path+'all_dataV5.csv'
all_data_fileV6 = origin_data_path+'all_dataV6.csv'

temp_result = origin_data_path + 'temp_result.csv'
submission_file = origin_data_path+'mars_tianchi_artist_plays_predict.csv'
artist_hour_pivot_file = origin_data_path + 'artist_hour.csv'
artist_day_pivot_file = origin_data_path+'artist_day.csv'
artist_day_download_pivot_file = origin_data_path +'artist_day_download.csv'
artist_day_collect_pivot_file = origin_data_path +'artist_day_collect.csv'

params_product_file = origin_data_path + 'params.txt'
feature_importance_file = origin_data_path + 'feature_importance.csv'
action_songs_fils = origin_data_path + 'action_songs.csv'
artist_week_play_cnt_pivot_file = origin_data_path + 'artist_week_play_cnt.csv'
artist_week_download_cnt_pivot_file = origin_data_path + 'artist_week_download_cnt.csv'
artist_week_collect_cnt_pivot_file = origin_data_path + 'artist_week_collect_cnt.csv'
artist_week_all_cnt_file = origin_data_path + 'artist_week_all_cnt.csv'
song_week_collect_cnt_pivot_file = origin_data_path + 'song_week_collect_cnt.csv'
artist_week_rank_cnt_pivot_file = origin_data_path+'artist_week_rank_cnt_pivot.csv'
artist_week_all_rank_cnt_file = origin_data_path+'artist_week_all_rank_cnt.csv'
artist_week_play_user_cnt_pivot_file = origin_data_path +'artist_week_play_user_cnt_pivot.csv'
artist_week_download_user_cnt_pivot_file = origin_data_path +'artist_week_download_user_cnt_pivot.csv'
artist_week_collect_user_cnt_pivot_file = origin_data_path +'artist_week_collect_user_cnt_pivot.csv'
artist_week_all_user_cnt_file = origin_data_path +'artist_week_all_user_cnt.csv'
artist_day_all_group_pivot_file = origin_data_path+'artist_day_all_group_pivot.csv'
artist_day_user_pivot_file = origin_data_path+'artist_day_user_pivot.csv'
artist_day_download_user_pivot_file = origin_data_path+'artist_day_download_user_pivot.csv'
artist_day_collect_user_pivot_file = origin_data_path+'artist_day_collect_user_pivot.csv'
artist_day_user_play_pivot_file = origin_data_path+'artist_day_user_play_pivot.csv'
artist_day_user_download_pivot_file = origin_data_path+'artist_day_user_download_pivot.csv'
artist_day_user_collect_pivot_file = origin_data_path+'artist_day_user_collect_pivot.csv'